apiVersion: v2
name: monitoring-umbrella
version: 0.1.0
dependencies:
  - name: k8s-monitoring
    version: 2.0.23
    repository: https://grafana.github.io/helm-charts
  - name: loki
    version: 6.29.0
    repository: https://grafana.github.io/helm-charts
  - name: grafana
    version: 8.12.0
    repository: https://grafana.github.io/helm-charts
