apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://auth.bakseter.net/oauth2
    trustForwardHeader: true
    authResponseHeadersRegex: ^X-
    headerField: X-My-User-Header-Test
