apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers
  namespace: oauth2-proxy
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Groups
      - X-Auth-Request-Preferred-Username
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: errors
  namespace: oauth2-proxy
spec:
  errors:
    status:
      - '401'
      - '403'
    service:
      name: oauth2-proxy
      port: 80
    query: '/oauth2/sign_in'
