argo-cd:
  global:
    domain: argocd.bakseter.net

    networkPolicy:
      create: true

  configs:
    repositories:
      argocd:
        url: https://github.com/bakseter/whpat

    cm:
      admin.enabled: true

    dex:
      enabled: false

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: argocd.bakseter.net
      tls: true
