argo-cd:
  global:
    domain: argocd.bakseter.net

    networkPolicy:
      create: true

  configs:
    repositories:
      argocd:
        url: https://github.com/bakseter/whpat

    cm:
      admin.enabled: true
      dex.config: |
        connectors:
          - type: authproxy
            id: oauth2-proxy
            name: OAuth2-Proxy
            config:
              userHeader: X-Forwarded-User
              groupHeader: X-Forwarded-Group
              staticGroups:
                - default

    dex:
      enabled: true

  server:
    ingress:
      enabled: false
      ingressClassName: traefik
      hostname: argocd.bakseter.net
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.middlewares: "oauth2-proxy-forwardauth@kubernetescrd"
      tls: true
