argo-cd:
  global:
    domain: argocd.bakseter.net
    revisionHistoryLimit: 1
    networkPolicy:
      create: false # TODO: enable

  configs:
    repositories:
      argocd:
        url: https://github.com/bakseter/whpah

    cm:
      admin.enabled: true
      dex.config: |
        connectors:
          - type: authproxy
            id: oauth2-proxy
            name: OAuth2-Proxy
            config:
              userHeader: X-Forwarded-User
              groupHeader: X-Forwarded-Group
              staticGroups:
                - default

    dex:
      enabled: true
      logLevel: debug

    params:
      server.insecure: true

  notifications:
    enabled: false
