argo-cd:
  global:
    domain: argocd.bakseter.net
    revisionHistoryLimit: 1
    networkPolicy:
      create: false # TODO: enable

  configs:
    repositories:
      argocd:
        url: https://github.com/bakseter/whpah

    cm:
      admin.enabled: true
      dex.config: |
        connectors:
          - type: authproxy
            id: oauth2-proxy
            name: OAuth2-Proxy
            config:
              userHeader: X-Auth-Request-User
              groupHeader: X-Auth-Request-Groups
              staticGroups:
                - default

    rbac:
      policy.default: ''
      policy.csv: |
        p, role:org-admin, *, get, *, allow
        p, role:org-admin, applications, sync, *, allow
        p, role:org-admin, applicationsets, sync, *, allow
        g, andreas_tkd@hotmail.com, role:org-admin
        g, 100303045794873106192, role:org-admin

    dex:
      enabled: true

    params:
      server.insecure: true
      dexserver.log.level: debug

  notifications:
    enabled: false
