oauth2-proxy:
  config:
    existingSecret: google-credentials
    configFile: |
      email_domains = ["*"]
      upstreams = ["static://200"]

  extraArgs:
    provider: google
    oidc-issuer-url: https://accounts.google.com
    code-challenge-method: S256
    redirect-url: https://auth.bakseter.net/oauth2/callback
    cookie-csrf-per-request: true
    cookie-domain: .bakseter.net
    whitelist-domain: .bakseter.net
    silence-ping-logging: true
    skip-provider-button: true

  revisionHistoryLimit: 1

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - auth.bakseter.net
    tls:
      - hosts:
          - auth.bakseter.net
        secretName: ingress-tls
