oauth2-proxy:
  config:
    existingSecret: google-credentials
    configFile: |
      email_domains = ["*"]
      upstreams = ["static://200"]
  extraArgs:
    provider: google
    oidc-issuer-url: https://accounts.google.com
    pass-authorization-header: true
    code-challenge-method: S256
    redirect-url: https://sso.bakseter.net/oauth2/callback
    cookie-csrf-per-request: true
    cookie-domain: .bakseter.net
    whitelist-domain: .bakseter.net
    silence-ping-logging: true
    set-xauthrequest: true
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - sso.bakseter.net
    tls:
    - hosts:
        - sso.bakseter.net
      secretName: ingress-tls
