apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend
  namespace: five31
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: Deployment
    name: backend
  updatePolicy:
    updateMode: 'Auto'
