apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/match-tag: "true"
    keel.sh/policy: force
    keel.sh/trigger: poll
  name: five31-backend
  namespace: five31
spec:
  replicas: 1
  selector:
    matchLabels:
      app: five31-backend
  template:
    metadata:
      labels:
        app: five31-backend
    spec:
      containers:
      - name: five31-backend
        image: ghcr.io/bakseter/five31/backend:latest
        env:
        - name: DATABASE_URL
          value: jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/postgres
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: five31-backend-secret
        ports:
        - containerPort: 8080
