apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: five31
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  serviceName: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:17-alpine
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATABASE_PASSWORD
                  name: database-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              mountPropagation: None
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: database
