apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: five31
spec:
  storageClassName: hcloud-volumes
  volumeName: five31-database # <-- reference PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
