kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: database
  namespace: five31
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
          ports:
            - protocol: TCP
              port: 5432
