kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.bakseter.net
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.bakseter.net
