apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres
  namespace: postgres
spec:
  encryptedData:
    password: AgBAHjik5LhUP62rCcMVORBOTRTEcLPjcmeoYuC7dAZQ9g1zUs50Bg7s26jhJQAYRE3D9NQWlDTryNqkeuxugJb/LkAX6Y3uneRjEKo5funI11AxCgbOKD416Oe3ff8yy5cbIdcxJK4hXiehxGfc5E2osZLDSPI76PgyCHD56HpnuOZH1AVc9J2mUdQY1lFjyFHqQaYC3AQPBMr2sRk2RdaO0rcCLN30BJBz6GXFI1nUOJlVJXg9sAHWey33sbX63ER4Xl1RsQmlCfBV2+4Ul/dIpRgLlCHpxF3tuyxNGCdPgBNuaBF1bfxJRd9fZBGo/m2IySwSI1TkYQ6EuYY8QGZZ1KtR/XzhRcSu5q+V5A6Y9+SSFWVEwL3zzCPUuuW986FQ7f7XXN0w3RbBVEiqkp385jxmHNYRmicohWjZBnjCuBWRj8ek08laWrWvz58Lj3XkWo5S8NGuiohgsi18TNH9Ng2VN6q0pcLkEJKjtHXFMhlukIF5SzTy8o9VGxALOahlAISsYizlStHStGaWFAicAITAWmbSM5xdhadZ8KTlzE8PUhohncWEIfrsfAM3QuzxxkGjU38LAR68x2wXJmBq29onmHb1vdZz0o5y5jdfXgvTzZkXHEIlLd8qI2XHNyngl0kfkYft0zP+k7ME34KfdoLWGaGqXzoW9VooahI1yturEdjIGnR/Zh+B/hxc8ChEnQjuVG7WtNbGtjI3qULDfr+r9LMRfH46sXGjDG4h/Q==
  template:
    metadata:
      name: postgres
      namespace: postgres
    type: Opaque
