apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
spec:
  instanceSelector:
    matchLabels:
      dashboards: 'grafana'
  datasource:
    name: loki
    type: loki
    access: proxy
    basicAuth: false
    url: http://monitoring-loki-gateway.monitoring.svc.cluster.local:80
    isDefault: false
