apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/match-tag: 'true'
    keel.sh/policy: force
    keel.sh/trigger: poll
  name: app
  namespace: spenn
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/bakseter/spenn:latest
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: database-config
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: database-config
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-secret
          ports:
            - containerPort: 8080
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 1001
