apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: app-vpa
  namespace: spenn
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: Deployment
    name: app
  updatePolicy:
    updateMode: 'Auto'
