apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/match-tag: "true"
    keel.sh/policy: force
    keel.sh/trigger: poll
  name: app
  namespace: spenn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/bakseter/spenn:latest
        env:
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_NAME
          value: postgres
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: database-secret
        ports:
        - containerPort: 8080
