apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-secret
  namespace: spenn
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBKSvDztdWOO7D3sAN0Za1ob0VoJCgcbmF2LhrK+q++TDKm87Qlw7LetYZrZ2FfqeXlLIZa3D62HXm8bInpWHY5J2ZxJE0V6gXt3fLiPOQGhj7v5NkZ0g+0kVZrv57KIuTil++vHLASYB0Agk+i8EYcsntIKvft1XkO3XhBgcl4mkx7QPw9tGweHCPc7n0qxjbJH2DyACAtEyCBglIq/63SjXINfBukEEu5M2qCq1ywesen9L9m8So+/w/psMs2u6D87TW5T76JiO/EGBZLaRq5n5LeeHnHV68kSu0yjnOHbiE2Yjr/iGR4XvxLjyhn3j82F+ShWv0lF0MqcEzcn64vXcYfLIypPA8EeEHDA4XLHUvb+7zedwFDqcfSeeh1QajaUJ6LmEAVuZrH6wjtZ/eMaiM3pIgQOX4DyPgmFNOtUI9QWDRjc22prsu4lZTHWicShux+c2/0oEtBNfXIYG/9lNWiGuHMl+Rigd6uSdxAOrGb8LytLv+orrxFk/RbZ99kap7lOIMwVlWgcZfKj4yvkAzZdEFBr+0yAqo7p1KsDTvXH6j+8tyJCuOzYvS2wa8+x5QqsylyJcT8pFnYMrXQCcJ4EKn9BYKCawpKpIL8Minp++Rz6xZmfUG+lExLK9FcX/IAe6huJe1vQR0v5CInv7KFfUrUS3l69we0s80/fPaf0xIDzSkCzJg1LSBXNHpwDfcl26zTrGUnGwlztF/eu8pO/M9ifLoj1TqCMB2mhA==
  template:
    metadata:
      name: database-secret
      namespace: spenn
