kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database
  namespace: spenn
spec:
  storageClassName: hcloud-volumes
  volumeName: spenn-database # <-- reference PV name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
