apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: spenn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  serviceName: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:17-alpine
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          securityContext:
            # allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              mountPropagation: None
              name: postgres-data
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: database
