apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: spenn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hcloud-volumes
  volumeName: imported-data
