apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: database
  namespace: spenn
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: StatefulSet
    name: database
  updatePolicy:
    updateMode: 'Auto'
